<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./wine.glb -t
Author: ilya.terekhin (https://sketchfab.com/ilya.terekhin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/classic-wine-bottle-with-label-7ce93c8c3db74d3eb6421b5579717938
Title: Classic wine bottle with label
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Material_0: THREE.Mesh;
			Material_2: THREE.Mesh;
			['printarea-1_3']: THREE.Mesh;
			['printarea-2_5']: THREE.Mesh;
		};
		materials: {
			Material_0: THREE.MeshStandardMaterial;
			Material_2: THREE.MeshStandardMaterial;
			['printarea-1_3']: THREE.MeshStandardMaterial;
			['printarea-2_5']: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/wine.glb');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group rotation={[-Math.PI / 2, 0, 0]}>
			<T.Group rotation={[Math.PI / 2, 0, 0]}>
				<T.Mesh geometry={gltf.nodes.Material_0.geometry} material={gltf.materials.Material_0} />
				<T.Mesh geometry={gltf.nodes.Material_2.geometry} material={gltf.materials.Material_2} />
				<T.Mesh
					geometry={gltf.nodes['printarea-1_3'].geometry}
					material={gltf.materials['printarea-1_3']}
				/>
				<T.Mesh
					geometry={gltf.nodes['printarea-2_5'].geometry}
					material={gltf.materials['printarea-2_5']}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
